version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - .env.development
    ports:
        - ${DB_PORT}:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

volumes:
  dbdata: